services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/home/vscode/app/node_modules
      - ../:/home/vscode/app:cached
    tty: true
    stdin_open: true

  redis:
    image: redis:latest

volumes:
  node_modules:
