name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node and authenticate to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@mito-shogi'       # package scope

      # Install all dependencies, including @mito-shogi/tsshogi-tpa
      - name: Install dependencies
        run: npm ci                  # or `npm install`
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ...existing build / test / deploy steps...
